export const erroresES: Record<string, string> = {
  USER_NOT_FOUND: "Usuario no encontrado",
  USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL: "Este usuario ya existe, utiliza otro correo",
  FAILED_TO_CREATE_USER: "No se pudo crear el usuario",
  FAILED_TO_CREATE_SESSION: "No se pudo iniciar sesión",
  FAILED_TO_UPDATE_USER: "No se pudo actualizar el usuario",
  FAILED_TO_GET_SESSION: "No se pudo obtener la sesión",
  INVALID_PASSWORD: "La contraseña no es válida",
  INVALID_EMAIL: "El correo no es válido",
  INVALID_EMAIL_OR_PASSWORD: "Correo o contraseña incorrectos",
  SOCIAL_ACCOUNT_ALREADY_LINKED: "La cuenta social ya está vinculada",
  PROVIDER_NOT_FOUND: "Proveedor no disponible",
  INVALID_TOKEN: "Token inválido",
  ID_TOKEN_NOT_SUPPORTED: "El token de identificación no es compatible",
  FAILED_TO_GET_USER_INFO: "No se pudo obtener la información del usuario",
  USER_EMAIL_NOT_FOUND: "El correo del usuario no fue encontrado",
  EMAIL_NOT_VERIFIED: "El correo no ha sido verificado",
  PASSWORD_TOO_SHORT: "La contraseña es demasiado corta",
  PASSWORD_TOO_LONG: "La contraseña es demasiado larga",
  USER_ALREADY_EXISTS: "El usuario ya existe",
  EMAIL_CAN_NOT_BE_UPDATED: "El correo no puede ser actualizado",
  CREDENTIAL_ACCOUNT_NOT_FOUND: "Cuenta no encontrada",
  SESSION_EXPIRED: "La sesión ha expirado",
  FAILED_TO_UNLINK_LAST_ACCOUNT: "No puedes desvincular la última cuenta",
  ACCOUNT_NOT_FOUND: "Cuenta no encontrada",
  USER_ALREADY_HAS_PASSWORD: "El usuario ya tiene una contraseña asignada",
};
